networks:
  appdata_default:
    external: true
    name: "appdata_default"

services:
  bazarr:
    container_name: "bazarr"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=UTC"
      - "UMASK=022"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "b5da1152203f"

    image: "linuxserver/bazarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v1.5.6-ls346 Build-date:- 2026-04-28T22:12:55+00:00"
      com.docker.compose.config-hash: "0ebde6d6707889880fbabf9623aac0bbd58dee6b3d4625e8f564491597a4f258"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:b9a53db1b5d6571a530b8a46660649fc642a1a2bdf03cf48f4e7a5e93a1aba1c"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "bazarr"
      com.docker.compose.service: "bazarr"
      com.docker.compose.version: "5.0.2"
      maintainer: "chbmb"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-04-28T22:12:55+00:00"
      org.opencontainers.image.description:
        "[Bazarr](https://www.bazarr.media/) is a companion application\
        \ to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define\
        \ your preferences by TV show or movie and Bazarr takes care of everything for you."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-bazarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "bb605b7c40f5baee75f1b86de014030374276c58"
      org.opencontainers.image.revision: "bb605b7c40f5baee75f1b86de014030374276c58"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-bazarr"
      org.opencontainers.image.title: "Bazarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-bazarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.5.6-ls346"

    logging:
      driver: "journald"
      options: {}

    mac_address: "da:58:21:6a:bb:09"

    networks:
      - "appdata_default"

    ports:
      - "6767:6767/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/bazarr:/config"
      - "/opt/appdata/data/media:/data/media"

    working_dir: "/"

  earthly-buildkitd:
    container_name: "earthly-buildkitd"

    entrypoint:
      - "/usr/bin/entrypoint.sh"
      - "buildkitd"
      - "--config=/etc/buildkitd.toml"

    environment:
      - "BUILDKIT_DEBUG=false"
      - "BUILDKIT_TCP_TRANSPORT_ENABLED=false"
      - "BUILDKIT_TLS_ENABLED=false"
      - "BUILDKIT_MAX_PARALLELISM=20"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "BUILDKIT_SETUP_CGROUPV2_ROOT=1"
      - "EARTHLY_RESET_TMP_DIR=false"
      - "EARTHLY_TMP_DIR=/tmp/earthly"
      - "BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371"
      - "BUILDKIT_STEP_LOG_MAX_SIZE=8388608"
      - "CACHE_SIZE_MB=0"
      - "CACHE_SIZE_PCT=0"
      - "NETWORK_MODE=cni"
      - "EARTHLY_GIT_HASH=c48905267920d5599e849e8e043f801c6baab94a"
      - "BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:531b303aa8ec03c29c2ceaa140eb0a6d32e6f6f3+build"
      - "EARTHLY_CACHE_VERSION=2"

    hostname: "28462a7d1a3e"

    image: "docker.io/earthly/buildkitd:v0.8.16"

    ipc: "private"

    labels:
      dev.earthly.built-by: ""
      dev.earthly.git-sha: "cb38f72663696d17d8393b1cc8bac66aed28faa2"
      dev.earthly.settingshash: "e9fe7910efadcc66"
      dev.earthly.version: "v0.8.15"

    logging:
      driver: "journald"
      options: {}

    network_mode: "bridge"

    ports:
      - "127.0.0.1:8371:8371/tcp"

    privileged: true

    security_opt:
      - "label=disable"

    volumes:
      - "855a0ba718fa3a26f40d612e366b05c0e62154f1a5b1e11584939a2e1dd8b66a:/var/lib/buildkit"
      - "earthly-cache:/tmp/earthly"

    working_dir: "/"

  jellyfin:
    container_name: "jellyfin"

    entrypoint:
      - "/init"

    environment:
      - "TZ=UTC"
      - "UMASK=022"
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "MALLOC_TRIM_THRESHOLD_=131072"
      - "ATTACHED_DEVICES_PERMS=/dev/dri /dev/dvb /dev/vchiq /dev/vc-mem /dev/video1? -type c"

    hostname: "fb3e3e990387"

    image: "linuxserver/jellyfin:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 10.11.8ubu2404-ls30 Build-date:- 2026-04-28T14:49:30+00:00"
      com.docker.compose.config-hash: "c3debcf653454598c5aa099069c465902ca9eb1ca469564c62e401eb1fc0aa73"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:cb108ea78c1b783f182062343e9ac0d26a5e95b39df68289653c6785b1896a5b"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "jellyfin"
      com.docker.compose.service: "jellyfin"
      com.docker.compose.version: "5.0.2"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-04-28T14:49:30+00:00"
      org.opencontainers.image.description:
        "[Jellyfin](https://github.com/jellyfin/jellyfin) is a Free\
        \ Software Media System that puts you in control of managing and streaming your media. It is an\
        \ alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user\
        \ devices via multiple apps. Jellyfin is descended from Emby's 3.5.2 release and ported to the\
        \ .NET Core framework to enable full cross-platform support. There are no strings attached, no\
        \ premium licenses or features, and no hidden agendas: just a team who want to build something\
        \ better and work together to achieve it."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-jellyfin"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "02317f6c678e618c96edaa3c12dc98844fb6e7cb"
      org.opencontainers.image.revision: "02317f6c678e618c96edaa3c12dc98844fb6e7cb"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-jellyfin"
      org.opencontainers.image.title: "Jellyfin"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-jellyfin/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "10.11.8ubu2404-ls30"

    logging:
      driver: "journald"
      options: {}

    mac_address: "22:20:38:81:ee:e3"

    networks:
      - "appdata_default"

    ports:
      - "8096:8096/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/jellyfin:/config"
      - "/opt/appdata/data/media:/data/media"

    working_dir: "/"

  lidarr:
    container_name: "lidarr"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "TZ=UTC"
      - "UMASK=022"
      - "PUID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/lidarr-temp"

    hostname: "ddc8b5a1cfa1"

    image: "linuxserver/lidarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 3.1.0.4875-ls26 Build-date:- 2026-04-29T04:42:15+00:00"
      com.docker.compose.config-hash: "2e8c07003fb53c456d47cd6e9821c61a94f7b0bf2daf866a00d29c8a7c5d0ee0"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:cbec8b4e232593dedc7548e30c7da336f040df4e50cf8b1b24273be48e6d0ea9"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "lidarr"
      com.docker.compose.service: "lidarr"
      com.docker.compose.version: "5.0.2"
      maintainer: "Roxedus,thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-04-29T04:42:15+00:00"
      org.opencontainers.image.description:
        "[Lidarr](https://github.com/lidarr/Lidarr) is a music collection\
        \ manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new tracks from\
        \ your favorite artists and will grab, sort and rename them. It can also be configured to automatically\
        \ upgrade the quality of files already downloaded when a better quality format becomes available."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-lidarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "d4fcdcb294afa324da08c7f6f84bbb5422d52130"
      org.opencontainers.image.revision: "d4fcdcb294afa324da08c7f6f84bbb5422d52130"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-lidarr"
      org.opencontainers.image.title: "Lidarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-lidarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "3.1.0.4875-ls26"

    logging:
      driver: "journald"
      options: {}

    mac_address: "da:74:d4:10:62:14"

    networks:
      - "appdata_default"

    ports:
      - "8686:8686/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/lidarr:/config"
      - "/opt/appdata/data:/data"

    working_dir: "/"

  nzbget:
    container_name: "nzbget"

    entrypoint:
      - "/init"

    environment:
      - "UMASK=022"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=UTC"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "1211f9a42711"

    image: "linuxserver/nzbget:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v26.1-ls241 Build-date:- 2026-05-01T16:13:58+00:00"
      com.docker.compose.config-hash: "3068c20703e4930d436dcff38e7d8e6b69d163b9ad249f7f54f2dc82ddaf90c5"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:a7dc5c8909676fdc3eefa30d5291b4aa9d4ff82f55fa1ab56a779cdff60d18ce"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "nzbget"
      com.docker.compose.service: "nzbget"
      com.docker.compose.version: "5.0.2"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-05-01T16:13:58+00:00"
      org.opencontainers.image.description:
        "[Nzbget](http://nzbget.com/) is a usenet downloader, written\
        \ in C++ and designed with performance in mind to achieve maximum download speed by using very\
        \ little system resources."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-nzbget"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "1075fa6aafe12514a50531a50177cf01d4230760"
      org.opencontainers.image.revision: "1075fa6aafe12514a50531a50177cf01d4230760"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-nzbget"
      org.opencontainers.image.title: "Nzbget"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-nzbget/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v26.1-ls241"

    logging:
      driver: "journald"
      options: {}

    mac_address: "ce:54:7c:a7:7b:38"

    networks:
      - "appdata_default"

    ports:
      - "6789:6789/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/nzbget:/config"
      - "/opt/appdata/data/usenet:/data/usenet"

    working_dir: "/"

  prowlarr:
    container_name: "prowlarr"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "TZ=UTC"
      - "UMASK=022"
      - "PUID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/prowlarr-temp"

    hostname: "8e3c43104adf"

    image: "linuxserver/prowlarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 2.3.5.5327-ls144 Build-date:- 2026-04-29T06:16:44+00:00"
      com.docker.compose.config-hash: "91fc2ff8fa7ac0ce8958455a49090aaf66e3c0e594e91e3a82896d753aa16bdb"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:05dd987588ea1be46fac6c8f527d5fdf477c2ee8df2b54239a0f36ed68588d8b"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "prowlarr"
      com.docker.compose.service: "prowlarr"
      com.docker.compose.version: "5.0.2"
      maintainer: "Roxedus,thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-04-29T06:16:44+00:00"
      org.opencontainers.image.description:
        "[Prowlarr](https://github.com/Prowlarr/Prowlarr) is a indexer\
        \ manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various\
        \ PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly\
        \ with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with\
        \ no per app Indexer setup required (we do it all).  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-prowlarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "e080d4c634ccd0b5e0a4f9b073ce1a5931e2ecde"
      org.opencontainers.image.revision: "e080d4c634ccd0b5e0a4f9b073ce1a5931e2ecde"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-prowlarr"
      org.opencontainers.image.title: "Prowlarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-prowlarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "2.3.5.5327-ls144"

    logging:
      driver: "journald"
      options: {}

    mac_address: "b6:38:58:99:63:f7"

    networks:
      - "appdata_default"

    ports:
      - "9696:9696/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/prowlarr:/config"

    working_dir: "/"

  radarr:
    container_name: "radarr"

    entrypoint:
      - "/init"

    environment:
      - "UMASK=022"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=UTC"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/radarr-temp"

    hostname: "ac91b061d9cb"

    image: "linuxserver/radarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 6.1.1.10360-ls301 Build-date:- 2026-05-03T17:38:36+00:00"
      com.docker.compose.config-hash: "8280e7082c01d7fdf4f8a9e6e3228362cf8ec7d63dd0e8bb289efebe0043e3b9"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:16ddf3c8351ac07da9ecb3a3251deb38fd675b56e6480f485f957ae440cf9b19"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "radarr"
      com.docker.compose.service: "radarr"
      com.docker.compose.version: "5.0.2"
      maintainer: "Roxedus,thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-05-03T17:38:36+00:00"
      org.opencontainers.image.description:
        "[Radarr](https://github.com/Radarr/Radarr) - A fork of Sonarr\
        \ to work with movies à la Couchpotato.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-radarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "097c8279f3e336c515f39c353eece93ff29842ac"
      org.opencontainers.image.revision: "097c8279f3e336c515f39c353eece93ff29842ac"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-radarr"
      org.opencontainers.image.title: "Radarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-radarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "6.1.1.10360-ls301"

    logging:
      driver: "journald"
      options: {}

    mac_address: "46:79:3b:7b:f2:68"

    networks:
      - "appdata_default"

    ports:
      - "7878:7878/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/radarr:/config"
      - "/opt/appdata/data:/data"

    working_dir: "/"

  seerr:
    command:
      - "npm"
      - "start"

    container_name: "seerr"

    entrypoint:
      - "docker-entrypoint.sh"

    environment:
      - "UMASK=022"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=UTC"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=22.22.1"
      - "YARN_VERSION=1.22.22"
      - "NODE_ENV=production"
      - "COMMIT_TAG=e4ee71ae459cd45b66ad59b4b90c01e102e28e49"

    hostname: "5cd40792fb58"

    image: "ghcr.io/seerr-team/seerr:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "63f3f4f78bbae8bd82063c8069a8df4d4ffcdee00f2016fd9540872a29c2f64b"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:7e913cab7edd69551e1bce0d291a43e786f0c2c671b2f7a540bf7d388c1fdcb9"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "seerr"
      com.docker.compose.service: "seerr"
      com.docker.compose.version: "5.0.2"
      org.opencontainers.image.created: "1776284252"
      org.opencontainers.image.description:
        "Open-source media request and discovery manager for Jellyfin,\
        \ Plex, and Emby."
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "e4ee71ae459cd45b66ad59b4b90c01e102e28e49"
      org.opencontainers.image.source: "https://github.com/seerr-team/seerr"
      org.opencontainers.image.title: "seerr"
      org.opencontainers.image.url: "https://github.com/seerr-team/seerr"
      org.opencontainers.image.version: "v3.2.0"

    logging:
      driver: "journald"
      options: {}

    networks:
      - "appdata_default"

    ports:
      - "5055:5055/tcp"

    restart: "unless-stopped"

    user: "node:node"

    volumes:
      - "/opt/appdata/config/seerr:/app/config"

    working_dir: "/app"

  sonarr:
    container_name: "sonarr"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=UTC"
      - "UMASK=022"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "SONARR_CHANNEL=v4-stable"
      - "SONARR_BRANCH=main"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/sonarr-temp"

    hostname: "110ca87f8fad"

    image: "linuxserver/sonarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 4.0.17.2952-ls310 Build-date:- 2026-05-02T00:12:18+00:00"
      com.docker.compose.config-hash: "3c79ec3d806489b459d62bfaeb791caeaa732a9b2d34907f92025d64d6c06e4c"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:10469694193448235b3225eaee3c614463424e8b9490faf619d9b8e24ce7e2b7"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "appdata"
      com.docker.compose.project.config_files: "/opt/appdata/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/opt/appdata"
      com.docker.compose.replace: "sonarr"
      com.docker.compose.service: "sonarr"
      com.docker.compose.version: "5.0.2"
      maintainer: "thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-05-02T00:12:18+00:00"
      org.opencontainers.image.description:
        "[Sonarr](https://sonarr.tv/) (formerly NZBdrone) is a PVR\
        \ for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your\
        \ favorite shows and will grab, sort and rename them. It can also be configured to automatically\
        \ upgrade the quality of files already downloaded when a better quality format becomes available.\
        \  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-sonarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "11af280dc80cf09b419617558e02380d9546a044"
      org.opencontainers.image.revision: "11af280dc80cf09b419617558e02380d9546a044"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-sonarr"
      org.opencontainers.image.title: "Sonarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-sonarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "4.0.17.2952-ls310"

    logging:
      driver: "journald"
      options: {}

    mac_address: "42:0d:f3:7f:b6:84"

    networks:
      - "appdata_default"

    ports:
      - "8989:8989/tcp"

    restart: "unless-stopped"

    volumes:
      - "/opt/appdata/config/sonarr:/config"
      - "/opt/appdata/data:/data"

    working_dir: "/"

version: "3.6"

volumes:
  855a0ba718fa3a26f40d612e366b05c0e62154f1a5b1e11584939a2e1dd8b66a:
    external: true
  earthly-cache:
    external: true
