require("modules.config.nvim-telescope")
require("modules.config.nvim-lspconfig.init")
require("modules.config.lualine")
require("modules.config.indent_blankline")
require("modules.config.gitsigns")
require("modules.config.nvim-dap")
require("modules.config.neo-tree")
